describe('Error Code Management', function () {
    function leadingZeroes(num, zeroes = 2) {
        return '0'.repeat(zeroes - Math.ceil(Math.log10(num + 1))) + num;
    }
    let i = 0;
    it(leadingZeroes(++i) + ' - Go to Documentation Errors App Management Section', function () {
        cy.visit('http://sjo-testapp1/docErrors/management.php', {})
		cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Log in (Wrong)', function () {
        cy.get('#email').type("wrong", { delay: 100 });
        cy.get('#password').type("wrong", { delay: 100 });
        cy.get('button').contains('Iniciar sesión').click();
        cy.get('#error').should('contain', 'Error, verifique usuario y contraseña!');
        cy.get('#password').clear();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Log in (Good) User Not Allowed', function () {
        cy.get('#email').clear();
        cy.get('#email').type("coatingtr", { delay: 100 });
        cy.get('#password').type("Cuacoro#44", { delay: 100 });
        cy.get('button').contains('Iniciar sesión').click();
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + " - Display error message 'User Not Allowed'", function () {
        cy.get('#swal2-title').contains("You don't have permissions to modify data");
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.clearCookies();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Log in (Good) User Allowed', function () {
        cy.visit('http://sjo-testapp1/docErrors/management.php', {});
        cy.wait(1000);
        cy.get('#email').type("wotracker", { delay: 100 });
        cy.get('#password').type("Microvention#44", { delay: 100 });
        cy.wait(1000);
        cy.get('button').contains('Iniciar sesión').click();
    });
    it(leadingZeroes(++i) + " - Show Error Code Management '", function () {
        cy.wait(1000);
        cy.get('button').contains(' Error Code').click();
        cy.wait(1000);
        cy.get('#ecDesc').should('not.be.disabled');
        cy.get('#ecDesc').should('have.value', '');
        cy.get('#errorAction').should('be.disabled');
        cy.get('#errorAction').should('have.value', '');
        cy.get('#severity').should('be.disabled');
        cy.get('#severity').should('contain', '');
        cy.get('#ecStatus').should('be.disabled');
        cy.get('#ecStatus').should('contain', '');
        cy.get('#btnSaveEC').should('be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'btn btn-outline-success');
        cy.get('#btnUpdtaEC').should('be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'd-none');
        cy.get('#btnCancelEC').should('be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'd-none');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Choose an Existing Error Code', function () {
        cy.wait(2000);
        cy.get('TD').contains('Test out of specification').click();
        cy.get('#ecDesc').should('not.be.disabled');
        cy.get('#ecDesc').should('have.value', 'Test out of specification');
        cy.get('#errorAction').should('not.be.disabled');
        cy.get('#errorAction').should('have.value', 'NCR');
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').should('contain', 'No traceability');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').should('contain', 'Active');
        cy.get('#btnSaveEC').should('be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'd-none');
        cy.get('#btnUpdtaEC').should('not.be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelEC').should('not.be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'btn btn-dark');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Clear the Fields with Cancel Button', function () {
        cy.wait(2000);
        cy.get('#btnCancelEC').click();
        cy.get('#ecDesc').should('not.be.disabled');
        cy.get('#ecDesc').should('have.value', '');
        cy.get('#errorAction').should('be.disabled');
        cy.get('#errorAction').should('have.value', '');
        cy.get('#severity').should('be.disabled');
        cy.get('#severity').should('contain', '');
        cy.get('#ecStatus').should('be.disabled');
        cy.get('#ecStatus').should('contain', '');
        cy.get('#btnSaveEC').should('be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'btn btn-outline-success');
        cy.get('#btnUpdtaEC').should('be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'd-none');
        cy.get('#btnCancelEC').should('be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'd-none');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Try to Insert an Existing Error Code', function () {
        cy.wait(2000);
        cy.get('#ecDesc').type("No traceability", { delay: 100 });
        cy.get('#ecDesc').type('{enter}');
        cy.get('#errorAction').should('not.be.disabled');
        cy.get('#errorAction').type("No traceability", { delay: 100 });
        cy.get('#errorAction').type('{enter}');
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').select('No traceability');
        cy.get('#severity').should('contain', 'No traceability');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').select('Active');
        cy.get('#ecStatus').should('contain', 'Active');
        cy.get('#btnSaveEC').should('not.be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'btn btn-success');
        cy.get('#btnUpdtaEC').should('be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'd-none');
        cy.get('#btnCancelEC').should('be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'd-none');
        cy.wait(2000);
        cy.get('#btnSaveEC').click();
    });
    it(leadingZeroes(++i) + " - Display error message 'Error' 'This action cannot be performed'", function () {
        cy.get('#swal2-title').contains('Error');
        cy.get('#swal2-html-container').contains('This action cannot be performed');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
    });
    it(leadingZeroes(++i) + ' - Insert a new Error Code', function () {
        cy.wait(2000);
        cy.get('#ecDesc').clear();
        cy.get('#errorAction').clear();
        cy.get('#ecDesc').type("Cypress Test", { delay: 100 });
        cy.get('#ecDesc').type('{enter}');
        cy.get('#errorAction').should('not.be.disabled');
        cy.get('#errorAction').type("NCR", { delay: 100 });
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').select('No traceability');
        cy.get('#severity').should('contain', 'No traceability');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').select('Active');
        cy.get('#ecStatus').should('contain', 'Active');
        cy.get('#btnSaveEC').should('not.be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'btn btn-success');
        cy.get('#btnUpdtaEC').should('be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'd-none');
        cy.get('#btnCancelEC').should('be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'd-none');
        cy.wait(2000);
        cy.get('#btnSaveEC').click();
    });
    it(leadingZeroes(++i) + " - Display success message 'Error Code added successfully'", function () {
        cy.get('#swal2-title').contains('Error Code added successfully');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Choose an Existing Error Code to be Changed', function () {
        cy.wait(2000);
        cy.get('button').contains(' Error Code').click();
        cy.wait(1000);
        cy.get('input[type="search"]').type("Cypress Test", { delay: 100 });
        cy.get('TD').contains('Cypress Test').click();
        cy.get('#ecDesc').should('not.be.disabled');
        cy.get('#ecDesc').should('have.value', 'Cypress Test');
        cy.get('#errorAction').should('not.be.disabled');
        cy.get('#errorAction').should('have.value', 'NCR');
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').should('contain', 'No traceability');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').should('contain', 'Active');
        cy.get('#btnSaveEC').should('be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'd-none');
        cy.get('#btnUpdtaEC').should('not.be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelEC').should('not.be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'btn btn-dark');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Change the Description, Action, Severity and Status a Document Error', function () {
        cy.wait(2000);
        cy.get('#ecDesc').type(" Changed", { delay: 100 });
        cy.get('#ecDesc').type('{enter}');
        cy.get('#errorAction').type(" Changed", { delay: 100 });
        cy.get('#errorAction').type('{enter}');
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').select('Missing or incorrect acceptance data');
        cy.get('#severity').should('contain', 'Missing or incorrect acceptance data');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').select('Inactive');
        cy.get('#ecStatus').should('contain', 'Inactive');
        cy.get('#btnSaveEC').should('be.disabled');
        cy.get('#btnSaveEC').should('have.class', 'd-none');
        cy.get('#btnUpdtaEC').should('not.be.disabled');
        cy.get('#btnUpdtaEC').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelEC').should('not.be.disabled');
        cy.get('#btnCancelEC').should('have.class', 'btn btn-dark');
        cy.wait(2000);
        cy.get('#btnUpdtaEC').click();
    });
    it(leadingZeroes(++i) + " - Display success message 'Error Code updated successfully'", function () {
        cy.get('#swal2-title').contains('Error Code updated successfully');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Verify the Error Code Was Changed', function () {
        cy.wait(2000);
        cy.get('button').contains(' Error Code').click();
        cy.wait(1000);
        cy.get('input[type="search"]').type("Cypress Test Changed", { delay: 100 });
        cy.get('TD').contains('Cypress Test Changed').click();
        cy.get('#ecDesc').should('not.be.disabled');
        cy.get('#ecDesc').should('have.value', 'Cypress Test Changed');
        cy.get('#errorAction').should('not.be.disabled');
        cy.get('#errorAction').should('have.value', 'NCR Changed');
        cy.get('#severity').should('not.be.disabled');
        cy.get('#severity').should('contain', 'Missing or incorrect acceptance data');
        cy.get('#ecStatus').should('not.be.disabled');
        cy.get('#ecStatus').should('contain', 'Inactive');
    });
});