let id = 1;
let number = "01";
function counter() {
  id++;
  if (id < 10) {
    number = `0${id}`;
  } else {
    number = id;
  }
}

beforeEach(() => {
  cy.visit("10.0.122.26:3000"); // Visita la página por primera vez
});

describe(`Allocator Site`, () => {
  it(`${number}: Load the web page`, () => {
    cy.get('#process').should('have.value', '');
    cy.get('#batch').should('not.exist');
    cy.get('#site').should('not.exist');
    cy.get('#userID').should('not.exist');
    cy.get('#password').should('not.exist');
    cy.get('#btnUpdate').should('be.disabled');
    cy.screenshot();
    cy.wait(1000);
  });
  describe('Update Batch Number', () => {
    counter();
    it(`${number}: Select Batch Number on process name field`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a wrong batch number`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('2006255461');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "Batch number not found"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('2006255461');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '2006255461');
      cy.get('#batch').should('have.class', 'is-invalid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a correct batch number`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The batch number turns green and the site field is enabled"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Select Fase I"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong user id"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong password`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type incorrect userID`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1005');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct password`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The update site button is enabled`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Click on update site button`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays message saying "Data saved successfully"`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('200625546');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '200625546');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.get('#btnUpdate').click();
      cy.get('#swal2-title').contains('Data updated successfully');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The change appears on the audit trail section"`, () => {
      cy.screenshot();
      cy.wait(1000);
    });
  });
  describe('Update Base Consec', () => {
    counter();
    it(`${number}: Select Batch Number on process name field`, () => {
      cy.get('#process').select('Batch Number');
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a wrong Base Consec`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('0');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "Batch number not found"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('0');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '0');
      cy.get('#batch').should('have.class', 'is-invalid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a correct Base Consec`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The Base Consec turns green and the site field is enabled"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Select Fase I"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong user id"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong password`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type incorrect userID`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1005');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct password`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The update site button is enabled`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Click on update site button`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays message saying "Data saved successfully"`, () => {
      cy.get('#process').select('Base Consec');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('1');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '1');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.get('#btnUpdate').click();
      cy.get('#swal2-title').contains('Data updated successfully');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The change appears on the audit trail section"`, () => {
      cy.screenshot();
      cy.wait(1000);
    });
  });
  describe('Update Hydak', () => {
    counter();
    it(`${number}: Select Hydak on process name field`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a wrong batch number`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('0');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "Batch number not found"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('012031011 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '012031011 - A');
      cy.get('#batch').should('have.class', 'is-invalid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type a correct Hydak`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The Hydak turns green and the site field is enabled"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Select Fase I"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong user id"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type wrong password`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type incorrect userID`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays error message saying "User or password incorrect"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1006');
      cy.get('#userID').type('{enter}');
      cy.wait(100);
      cy.get('#password').type('1005');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-invalid');
      cy.get('#password').should('have.class', 'is-invalid');
      cy.get('button').contains('OK').click();
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct userID`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Type correct password`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1005');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The update site button is enabled`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: Click on update site button`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The systems displays message saying "Data saved successfully"`, () => {
      cy.get('#process').select('Hydak');
      cy.get('#process').should('have.class', 'is-valid')
      cy.get('#batch').should('be.exist');
      cy.get('#site').should('be.exist');
      cy.get('#userID').should('be.exist');
      cy.get('#password').should('be.exist');
      cy.get('#btnUpdate').should('be.disabled');
      cy.get('#batch').should('be.enabled');
      cy.get('#site').should('be.disabled');
      cy.get('#userID').should('be.disabled');
      cy.get('#password').should('be.disabled');
      cy.get('#batch').type('01203101 - A');
      cy.get('#batch').type('{enter}');
      cy.get('#batch').should('have.value', '01203101 - A');
      cy.get('#batch').should('have.class', 'is-valid');
      cy.get('#site').select('Fase I');
      cy.get('#userID').type('1005');
      cy.get('#userID').type('{enter}');
      cy.get('#userID').type('{enter}');
      cy.get('#password').type('1006');
      cy.get('#password').type('{enter}');
      cy.get('#userID').should('have.class', 'is-valid');
      cy.get('#password').should('have.class', 'is-valid');
      cy.get('#btnUpdate').click();
      cy.get('#swal2-title').contains('Data updated successfully');
      cy.screenshot();
      cy.wait(1000);
    });
    counter();
    it(`${number}: The change appears on the audit trail section"`, () => {
      cy.screenshot();
      cy.wait(1000);
    });
  });
});


