describe('Base Consecutive', () => {
  beforeEach(function () {
    cy.visit('http://localhost/coatingtracker/crosslinker.php');
  });

  // Define una variable global para almacenar el valor
  var consecutive = 0;
  var num = 0;
  // Función que suma 1 a la variable
  function sumConsecutive() {
    consecutive = "";
    num += 1;
    if (num < 10) {
      consecutive = '0' + num + ' - ';
    } else {
      consecutive = num + ' - ';
    }
  }
  describe('Crosslinker interface CER1', () => {
    sumConsecutive();
    it(`${consecutive}Go to Desmodur interface`, function () {
      cy.visit("http://localhost/coatingtracker/crosslinker.php");
    });
    sumConsecutive();
    it(`${consecutive}Select Consecutive Number`, function () {
      cy.get("#lotNumber").select("67");
    });
    sumConsecutive();
    it(`${consecutive}Select Total Mixture`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX grams`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX Rev`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX Solution Lot`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Grams`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Rev`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Solution Lot`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
    });
    sumConsecutive();
    it(`${consecutive}Enter Scale ED`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
    });
    sumConsecutive();
    it(`${consecutive}Enter Mixer ED`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
    });
    sumConsecutive();
    it(`${consecutive}Enter Mixing Solution`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
    });
    sumConsecutive();
    it(`${consecutive}Enter User`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
    });
    sumConsecutive();
    it(`${consecutive}Enter Password`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
      cy.get("#usr").type("{enter}");
      cy.get("#pwd").type("1111");
    });
    sumConsecutive();
    it(`${consecutive}Click on save button`, function () {

    });
    sumConsecutive();
    it(`${consecutive}The system display "Display message "Data saved successfully!`, function () {
      cy.get("#lotNumber").select("67");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
      cy.get("#usr").type("{enter}");
      cy.get("#pwd").type("1111");
      cy.get("#pwd").type("{enter}");
      cy.get("#saveBut").click();
      cy.wait(100);
      cy.get('#swal2-title').contains('Data saved successfully!');
    });
  });
  describe('Crosslinker interface CER2', () => {
    sumConsecutive();
    it(`${consecutive}Go to Desmodur interface`, function () {
      cy.visit("http://localhost/coatingtracker/crosslinker.php");
    });
    sumConsecutive();
    it(`${consecutive}Select Consecutive Number`, function () {
      cy.get("#lotNumber").select("68");
    });
    sumConsecutive();
    it(`${consecutive}Select Total Mixture`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX grams`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX Rev`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
    });
    sumConsecutive();
    it(`${consecutive}Enter CX Solution Lot`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Grams`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Rev`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
    });
    sumConsecutive();
    it(`${consecutive}Enter Dowanol Solution Lot`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
    });
    sumConsecutive();
    it(`${consecutive}Enter Scale ED`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
    });
    sumConsecutive();
    it(`${consecutive}Enter Mixer ED`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
    });
    sumConsecutive();
    it(`${consecutive}Enter Mixing Solution`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
    });
    sumConsecutive();
    it(`${consecutive}Enter User`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
    });
    sumConsecutive();
    it(`${consecutive}Enter Password`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
      cy.get("#usr").type("{enter}");
      cy.get("#pwd").type("1111");
    });
    sumConsecutive();
    it(`${consecutive}Click on save button`, function () {

    });
    sumConsecutive();
    it(`${consecutive}The system display "Display message "Data saved successfully!`, function () {
      cy.get("#lotNumber").select("68");
      cy.get("#grams").select("1000");
      cy.get("#cx").should("be.enabled");
      cy.get("#cx").type("0.735");
      cy.get("#cx").type("{enter}");
      cy.get("#cxRev").type("A");
      cy.get("#cxRev").type("{enter}");
      cy.get("#cxLot").type("0000310321");
      cy.get("#cxLot").type("{enter}");
      cy.get("#dowanol").type("6.615");
      cy.get("#dowanol").type("{enter}");
      cy.get("#dowRev").should("be.enabled");
      cy.get("#dowRev").type("B");
      cy.get("#dowRev").type("{enter}");
      cy.get("#dowLot").should("be.enabled");
      cy.get("#dowLot").type("0000376838");
      cy.get("#dowLot").type("{enter}");
      cy.get("#scale").type("ED2119-019");
      cy.get("#scale").type("{enter}");
      cy.get("#mixer").type("ED2206-012");
      cy.get("#mixer").type("{enter}");
      cy.get("#speed").type("8");
      cy.get("#speed").type("{enter}");
      cy.get("#usr").type("1111");
      cy.get("#usr").type("{enter}");
      cy.get("#pwd").type("1111");
      cy.get("#pwd").type("{enter}");
      cy.get("#saveBut").click();
      cy.wait(100);
      cy.get('#swal2-title').contains('Data saved successfully!');
    });
  });
});