describe('User Management', function () {
    function leadingZeroes(num, zeroes = 2) {
        return '0'.repeat(zeroes - Math.ceil(Math.log10(num + 1))) + num;
    }
    let i = 0;
    it(leadingZeroes(++i) + ' - Go to Documentation Errors App Management Section', function () {
        cy.visit('http://sjo-testapp1/docErrors/management.php', {})
		cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Log in (Wrong)', function () {
        cy.get('#email').type("wrong", { delay: 100 });
        cy.get('#password').type("wrong", { delay: 100 });
        cy.get('button').contains('Iniciar sesión').click();
        cy.get('#error').should('contain', 'Error, verifique usuario y contraseña!');
        cy.get('#password').clear();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Log in (Good) User Not Allowed', function () {
        cy.get('#email').clear();
        cy.get('#email').type("coatingtr", { delay: 100 });
        cy.get('#password').type("Cuacoro#44", { delay: 100 });
        cy.get('button').contains('Iniciar sesión').click();
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + " - Display error message 'User Not Allowed'", function () {
        cy.get('#swal2-title').contains("You don't have permissions to modify data");
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.clearCookies();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Log in (Good) User Allowed', function () {
        cy.visit('http://sjo-testapp1/docErrors/management.php', {});
        cy.wait(1000);
        cy.get('#email').type("wotracker", { delay: 100 });
        cy.get('#password').type("Microvention#44", { delay: 100 });
        cy.wait(1000);
        cy.get('button').contains('Iniciar sesión').click();
    });
    it(leadingZeroes(++i) + ' - Show User Management', function () {
        cy.wait(1000);
        cy.get('button').contains(' User').click();
        cy.wait(1000);
        cy.get('#userEmail').should('not.be.disabled');
        cy.get('#userEmail').should('have.value', '');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', '');
        cy.get('#userStatus').should('be.disabled');
        cy.get('#userStatus').should('contain', '');
        cy.get('#userLevel').should('be.disabled');
        cy.get('#userLevel').should('contain', '');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-outline-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Try to Find an User Name With a Wrong Email', function () {
        cy.wait(2000);
        cy.get('#userEmail').type("rodolfo.vargas@microvention.con", { delay: 100 });
        cy.get('#userEmail').type('{enter}');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', '');
        cy.get('#userStatus').should('be.disabled');
        cy.get('#userStatus').should('contain', '');
        cy.get('#userLevel').should('be.disabled');
        cy.get('#userLevel').should('contain', '');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-outline-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + " - Display error message 'Error, Email not found'", function () {
        cy.get('#swal2-title').contains('Error');
        cy.get('#swal2-html-container').contains('Email not found');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Choose an Existing User', function () {
        cy.wait(2000);
        cy.get('TD').contains('Vargas Viquez Rodolfo').click();
        cy.get('#userEmail').should('not.be.disabled');
        cy.get('#userEmail').should('have.value', 'rodolfo.vargas@microvention.com');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Vargas Viquez Rodolfo');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'd-none');
        cy.get('#btnUpdtaUser').should('not.be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelUser').should('not.be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'btn btn-dark');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Try to Update a User With a Wrong Email', function () {
        cy.wait(2000);
        cy.get('#userEmail').clear();
        cy.get('#userEmail').type("rodolfo.vargas@microvention.con", { delay: 100 });
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', '');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'd-none');
        cy.get('#btnUpdtaUser').should('not.be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelUser').should('not.be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'btn btn-dark');
        cy.wait(2000);
        cy.get('#btnUpdtaUser').click();
    });
    it(leadingZeroes(++i) + " - Display error message 'Verify the user email'", function () {
        cy.get('#swal2-title').contains("Verify the user email");
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Clear the Fields with Cancel Button', function () {
        cy.wait(2000);
        cy.get('#btnCancelUser').click();
        cy.get('#userEmail').should('not.be.disabled');
        cy.get('#userEmail').should('have.value', '');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', '');
        cy.get('#userStatus').should('be.disabled');
        cy.get('#userStatus').should('contain', '');
        cy.get('#userLevel').should('be.disabled');
        cy.get('#userLevel').should('contain', '');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-outline-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Try to Insert an Existing User', function () {
        cy.wait(2000);
        cy.get('#userEmail').type("rodolfo.vargas@microvention.com", { delay: 100 });
        cy.get('#userEmail').type('{enter}');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Vargas Viquez Rodolfo');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').select('Active');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').select('Admin');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('not.be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
        cy.get('#btnSaveUser').click();
    });
    it(leadingZeroes(++i) + " - Display error message 'Error' 'This action cannot be performed'", function () {
        cy.get('#swal2-title').contains('Error');
        cy.get('#swal2-html-container').contains('This action cannot be performed');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
    });
    it(leadingZeroes(++i) + ' - Tray to Insert a new User With a Wrong Email', function () {
        cy.wait(2000);
        cy.get('#userEmail').clear();
        cy.get('#userEmail').type("juan.sanchez@microvention.com", { delay: 100 });
        cy.get('#userEmail').type('{enter}');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Sanchez Arias Juan');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').select('Active');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').select('Admin');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('not.be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
        cy.get('#userEmail').clear();
        cy.get('#userEmail').type("juan.sanchez@microvention.co", { delay: 100 });
        cy.get('#userLevel').select('Admin');
        cy.wait(2000);
        cy.get('#btnSaveUser').click();
    });
    it(leadingZeroes(++i) + " - Display error message 'Verify the user email'", function () {
        cy.get('#swal2-title').contains("Verify the user email");
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Insert a new User', function () {
        cy.wait(2000);
        cy.get('#userEmail').clear();
        cy.get('#userEmail').type("juan.sanchez@microvention.com", { delay: 100 });
        cy.get('#userEmail').type('{enter}');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Sanchez Arias Juan');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').select('Active');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').select('Admin');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('not.be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'btn btn-success');
        cy.get('#btnUpdtaUser').should('be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'd-none');
        cy.get('#btnCancelUser').should('be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'd-none');
        cy.wait(2000);
        cy.get('#btnSaveUser').click();
    });
    it(leadingZeroes(++i) + " - Display success message 'User added successfully'", function () {
        cy.get('#swal2-title').contains('User added successfully');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Choose an Existing User to be Changed', function () {
        cy.wait(2000);
        cy.get('button').contains(' User').click();
        cy.wait(1000);
        cy.get('input[type="search"]').type("Sanchez Arias Juan", { delay: 100 });
        cy.get('TD').contains('Sanchez Arias Juan').click();
        cy.get('#userEmail').should('not.be.disabled');
        cy.get('#userEmail').should('have.value', 'juan.sanchez@microvention.com');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Sanchez Arias Juan');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').should('contain', 'Active');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').should('contain', 'Admin');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'd-none');
        cy.get('#btnUpdtaUser').should('not.be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelUser').should('not.be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'btn btn-dark');
        cy.wait(2000);
    });
    it(leadingZeroes(++i) + ' - Change the Status and Role a User', function () {
        cy.wait(2000);
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').select('Inactive');
        cy.get('#userStatus').should('contain', 'Inactive');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').select('QC');
        cy.get('#userLevel').should('contain', 'QC');
        cy.get('#btnSaveUser').should('be.disabled');
        cy.get('#btnSaveUser').should('have.class', 'd-none');
        cy.get('#btnUpdtaUser').should('not.be.disabled');
        cy.get('#btnUpdtaUser').should('have.class', 'btn btn-warning');
        cy.get('#btnCancelUser').should('not.be.disabled');
        cy.get('#btnCancelUser').should('have.class', 'btn btn-dark');
        cy.wait(2000);
        cy.get('#btnUpdtaUser').click();
    });
    it(leadingZeroes(++i) + " - Display success message 'User updated successfully'", function () {
        cy.get('#swal2-title').contains('User updated successfully');
        cy.wait(2000);
        cy.get('button').contains('OK').click();
        cy.wait(1000);
    });
    it(leadingZeroes(++i) + ' - Verify the User Was Changed', function () {
        cy.wait(2000);
        cy.get('button').contains(' User').click();
        cy.wait(1000);
        cy.get('input[type="search"]').type("Sanchez Arias Juan", { delay: 100 });
        cy.get('TD').contains('Sanchez Arias Juan').click();
        cy.get('#userEmail').should('not.be.disabled');
        cy.get('#userEmail').should('have.value', 'juan.sanchez@microvention.com');
        cy.get('#userName').should('be.disabled');
        cy.get('#userName').should('have.value', 'Sanchez Arias Juan');
        cy.get('#userStatus').should('not.be.disabled');
        cy.get('#userStatus').should('contain', 'Inactive');
        cy.get('#userLevel').should('not.be.disabled');
        cy.get('#userLevel').should('contain', 'QC');
    });
});